// Use of this source code is governed by a MIT license that can be found in the LICENSE file.
// Giorgis (habtom@giorgis.io)

package avcodec

//#cgo pkg-config: libavcodec
//#include <libavcodec/avcodec.h>
import "C"

const (
	AV_CODEC_FLAG_UNALIGNED            = uint(C.AV_CODEC_FLAG_UNALIGNED)
	AV_CODEC_FLAG_QSCALE               = uint(C.AV_CODEC_FLAG_QSCALE)
	AV_CODEC_FLAG_4MV                  = uint(C.AV_CODEC_FLAG_4MV)
	AV_CODEC_FLAG_OUTPUT_CORRUPT       = uint(C.AV_CODEC_FLAG_OUTPUT_CORRUPT)
	AV_CODEC_FLAG_QPEL                 = uint(C.AV_CODEC_FLAG_QPEL)
	AV_CODEC_FLAG_PASS1                = uint(C.AV_CODEC_FLAG_PASS1)
	AV_CODEC_FLAG_PASS2                = uint(C.AV_CODEC_FLAG_PASS2)
	AV_CODEC_FLAG_LOOP_FILTER          = uint(C.AV_CODEC_FLAG_LOOP_FILTER)
	AV_CODEC_FLAG_GRAY                 = uint(C.AV_CODEC_FLAG_GRAY)
	AV_CODEC_FLAG_PSNR                 = uint(C.AV_CODEC_FLAG_PSNR)
	AV_CODEC_FLAG_TRUNCATED            = uint(C.AV_CODEC_FLAG_TRUNCATED)
	AV_CODEC_FLAG_INTERLACED_DCT       = uint(C.AV_CODEC_FLAG_INTERLACED_DCT)
	AV_CODEC_FLAG_LOW_DELAY            = uint(C.AV_CODEC_FLAG_LOW_DELAY)
	AV_CODEC_FLAG_GLOBAL_HEADER        = uint(C.AV_CODEC_FLAG_GLOBAL_HEADER)
	AV_CODEC_FLAG_BITEXACT             = uint(C.AV_CODEC_FLAG_BITEXACT)
	AV_CODEC_FLAG_AC_PRED              = uint(C.AV_CODEC_FLAG_AC_PRED)
	AV_CODEC_FLAG_INTERLACED_ME        = uint(C.AV_CODEC_FLAG_INTERLACED_ME)
	AV_CODEC_FLAG_CLOSED_GOP           = uint(C.AV_CODEC_FLAG_CLOSED_GOP)
	AV_CODEC_FLAG2_FAST                = uint(C.AV_CODEC_FLAG2_FAST)
	AV_CODEC_FLAG2_NO_OUTPUT           = uint(C.AV_CODEC_FLAG2_NO_OUTPUT)
	AV_CODEC_FLAG2_LOCAL_HEADER        = uint(C.AV_CODEC_FLAG2_LOCAL_HEADER)
	AV_CODEC_FLAG2_DROP_FRAME_TIMECODE = uint(C.AV_CODEC_FLAG2_DROP_FRAME_TIMECODE)
	AV_CODEC_FLAG2_CHUNKS              = uint(C.AV_CODEC_FLAG2_CHUNKS)
	AV_CODEC_FLAG2_IGNORE_CROP         = uint(C.AV_CODEC_FLAG2_IGNORE_CROP)
	AV_CODEC_FLAG2_SHOW_ALL            = uint(C.AV_CODEC_FLAG2_SHOW_ALL)
	AV_CODEC_FLAG2_EXPORT_MVS          = uint(C.AV_CODEC_FLAG2_EXPORT_MVS)
	AV_CODEC_FLAG2_SKIP_MANUAL         = uint(C.AV_CODEC_FLAG2_SKIP_MANUAL)
	AV_CODEC_FLAG2_RO_FLUSH_NOOP       = uint(C.AV_CODEC_FLAG2_RO_FLUSH_NOOP)
)
